services:
  web:
    container_name: k9-frontend
    image: node:23.0.0
    working_dir: /app/web
    volumes:
      - './web:/app/web'
    ports:
      - '5000:5173'
    command: [ 'npm', 'run', 'dev' ]

  db:
        container_name: k9-db
        image: postgres:16
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=default
        ports:
          - '4000:5432'
        volumes:
          - ./db:/var/lib/postgresql/data

volumes:
  db:
    driver: local